import { config } from "./config";

export const API = {
  accessToken: config?.result?.endpoint?.accessToken,
  approveRules: "",
  balance: config?.result?.endpoint?.balance,
  changePassword: config?.result?.endpoint?.changePassword,
  eventType: "",
  group: config?.result?.endpoint?.group,
  history: "",
  inPlayAndPopularEvents: config?.result?.endpoint?.inPlayAndPopularEvents,
  inplayEvents: "",
  ladder: config?.result?.endpoint?.ladder,
  login: config?.result?.endpoint?.login,
  menu: "",
  mobileStakes: "",
  notification: config?.result?.endpoint?.notification,
  odds: config?.result?.endpoint?.odds,
  oneClick: "",
  openEvents: "",
  order: config?.result?.endpoint?.order,
  orderCount: "",
  orderList: "",
  pastEvents: "",
  pnl: "",
  reportPnl: "",
  reportTransfer: "",
  rules: "",
  serverTime: "",
  stats: "",
  cricketScore: "",
  updateButtonValues: "https://odddb.com/lotusAdmin/setButtonValue.php",
  activityLog: "https://odddb.com/activity_log.php",
  casinoResults: "https://odddb.com/casinoResult.php",
  singleResults: "",
  buttonValue: config?.result?.endpoint?.buttonValue,
  changeTheme: "https://odddb.com/changeTheme.php",
  register: "",
  deposit: config?.result?.endpoint?.depositIframe,
  withdraw: config?.result?.endpoint?.withdrawIframe,
  message: "",
  ourCasino: config?.result?.endpoint?.auraCasino,
  diamondCasino: config?.result?.endpoint?.diamondCasino,
  auraCasino: "",
  casinoType:config?.result?.settings?.casino,
  myMarket:config?.result?.endpoint?.myMarket,
  competition:config?.result?.endpoint?.competition,
  searchEvent:config?.result?.endpoint?.searchEvent,
  currentBets:config?.result?.endpoint?.currentBets,
  cache:config?.result?.endpoint?.cache,
  interval:config?.result?.settings?.interval,
  exposure:config?.result?.endpoint?.exposure,
  accountStatement:config?.result?.endpoint?.accountStatement,
  settledBets:config?.result?.endpoint?.settledBets,
  siteUrl:config?.result?.settings?.siteUrl,
  whatsApp:config?.result?.endpoint?.whatsapp
};
