import { config } from "./config";

export const API = {
  accessToken: config?.result?.endpoint?.accessToken,
  approveRules: "",
  balance: config?.result?.endpoint?.balance,
  changePassword: config?.result?.endpoint?.changePassword,
  eventType: "",
  group: config?.result?.endpoint?.group,
  history: "",
  inPlayAndPopularEvents: config?.result?.endpoint?.inPlayAndPopularEvents,
  inplayEvents: "",
  ladder: config?.result?.endpoint?.ladder,
  login: config?.result?.endpoint?.login,
  menu: "",
  mobileStakes: "",
  notification: config?.result?.endpoint?.notification,
  odds: config?.result?.endpoint?.odds,
  oneClick: "",
  openEvents: "",
  order: config?.result?.endpoint?.order,
  orderCount: "",
  orderList: "",
  pastEvents: "",
  pnl: "",
  reportPnl: "",
  reportTransfer: "",
  rules: "",
  serverTime: "",
  stats: "",
  cricketScore: "",
  updateButtonValues: "https://odddb.com/lotusAdmin/setButtonValue.php",
  activityLog: "https://odddb.com/activity_log.php",
  casinoResults: "https://odddb.com/casinoResult.php",
  singleResults: "",
  buttonValue: config?.result?.endpoint?.buttonValue,
  changeTheme: "https://odddb.com/changeTheme.php",
  register: config?.result?.endpoint?.register,
  deposit: config?.result?.endpoint?.depositIframe,
  withdraw: config?.result?.endpoint?.withdrawIframe,
  message: "",
  ourCasino: config?.result?.endpoint?.auraCasino,
  diamondCasino: config?.result?.endpoint?.diamondCasino,
  auraCasino: "",
  casinoType: config?.result?.settings?.casino,
  myMarket: config?.result?.endpoint?.myMarket,
  competition: config?.result?.endpoint?.competition,
  searchEvent: config?.result?.endpoint?.searchEvent,
  currentBets: config?.result?.endpoint?.currentBets,
  cache: config?.result?.endpoint?.cache,
  interval: config?.result?.settings?.interval,
  exposure: config?.result?.endpoint?.exposure,
  accountStatement: config?.result?.endpoint?.accountStatement,
  settledBets: config?.result?.endpoint?.settledBets,
  siteUrl: config?.result?.settings?.siteUrl,
  whatsApp: config?.result?.endpoint?.whatsapp,
  otp:config?.result?.endpoint?.otp,
  liveCasinoWolf:config?.result?.endpoint?.liveCasinoWolf,
  slotWolf:config?.result?.endpoint?.slotsWolf,
  liveCasinoIFrame:config?.result?.endpoint?.liveCasinoIframe,
  auraWolf:config?.result?.endpoint?.auraWolf
};

export const Settings = {
  bonus: config?.result?.settings?.bonus,
  deposit: config?.result?.settings?.deposit,
  withdraw: config?.result?.settings?.withdraw,
  register: config?.result?.settings?.registration,
  demoLogin: config?.result?.settings?.demoLogin,
  disabledDevtool:config?.result?.settings?.disabledDevtool,
  otp:config?.result?.settings?.otp,
  casinoCurrency:config?.result?.settings?.casinoCurrency
};
